Make level-2
creator-max/AutoPark pull request #2
Opened 2021-10-28 16:33 UTC by creator-max

Add Vehicle class. Implement IComporable for Vehicle.

2021-10-29 18:35 UTC, PushMeNow requested changes

2021-10-29 18:35 UTC, PushMeNow commented on AutoPark/Vehicle.cs
> +        public VehicleType VehicleType { get; }
@kuzmiich I don't see the reason why here need  all accessors. It's correct he is using autoprop.

2021-10-29 18:35 UTC, PushMeNow commented on AutoPark/Vehicle.cs
> +        public ushort YearOfIssue { get; }
All props have to be initialized by ctor. 'init' accessor useless here

2021-10-29 18:35 UTC, PushMeNow commented on AutoPark/Vehicle.cs
> +        public double Weight { get; }
Why they cannot? Weight of vehicle is not editable property.

2021-10-29 18:35 UTC, PushMeNow commented on AutoPark/VehicleHelper.cs
> +        public static void PrintVehiclesOnConsole(Vehicle[] vehicles)
@kuzmiich It is helper for vehicle so generic will destroy whole logic of the helper. I agree with renaming but better PrintVehicles

2021-10-29 20:20 UTC, creator-max commented on AutoPark/Vehicle.cs
> +        public double GetCalcTaxPerMonth() => Weight * 0.0013 +
Thanks, fixed

2021-10-29 20:20 UTC, creator-max commented on AutoPark/Vehicle.cs
> +                return this.GetCalcTaxPerMonth().CompareTo(other.GetCalcTaxPerMonth());
Thanks, fixed

2021-10-29 20:21 UTC, creator-max commented on AutoPark/VehicleHelper.cs
> +        public static void PrintVehiclesOnConsole(Vehicle[] vehicles)
Thanks, fixed

2021-10-30 13:53 UTC, kuzmiich approved these changes

2021-10-31 09:53 UTC, kuzmiich approved these changes

2021-10-31 10:16 UTC, PushMeNow approved these changes

2021-10-31 13:12 UTC, merged