Level 3
creator-max/AutoPark pull request #3
Opened 2021-11-01 16:54 UTC by creator-max

Add Engines. Update Vehicle, override Equals() for Vehicle. Update VehicleHelper.

2021-11-01 17:06 UTC, kuzmiich commented on AutoPark/VehicleHelper.cs
> +                for (int j = i + 1; j < vehicles.Count; j++)
Redundant second loop

2021-11-01 17:06 UTC, kuzmiich commented on AutoPark/ElectricalEngine.cs
> +            : base("Electrical", 0.1d)
Remove 0.1`d`, or add to DieselEngine

2021-11-01 18:16 UTC, creator-max commented on AutoPark/Vehicle.cs
> +            if (!(obj is Vehicle other))
Thanks, fixed

2021-11-01 18:17 UTC, creator-max commented on AutoPark/ElectricalEngine.cs
> +            : base("Electrical", 0.1d)
Thanks, fixed. Added "d" everywhere

2021-11-01 19:03 UTC, kuzmiich approved these changes
Cool!

2021-11-02 15:39 UTC, PushMeNow requested changes

2021-11-02 15:39 UTC, PushMeNow commented on AutoPark/CombustionEngine.cs
> +        public double FuelConsumptionPer100 { get; private protected set; }
Don't see the sense in private protected

2021-11-02 15:39 UTC, PushMeNow commented on AutoPark/Vehicle.cs
> +                return false;
Redundant because  below you have <code>obj is Vehicle</code> condition

2021-11-02 15:53 UTC, creator-max commented on AutoPark/CombustionEngine.cs
> +        public double FuelConsumptionPer100 { get; private protected set; }
Thanks, fixed

2021-11-02 15:53 UTC, creator-max commented on AutoPark/Vehicle.cs
> +                return false;
Thanks, fixed

2021-11-03 18:22 UTC, PushMeNow approved these changes

2021-11-03 20:45 UTC, merged