Make level-5.
creator-max/AutoPark pull request #5
Opened 2021-11-08 18:33 UTC by creator-max

Added custom collections at this level. Developed class and methods for reading collections from .csv files.

2021-11-11 21:46 UTC, PushMeNow requested changes

2021-11-11 21:46 UTC, PushMeNow commented on AutoPark/Program.cs
> +            const string path = @"C:\Users\ASUS\source\repos\AutoPark\AutoPark\Data\";
Sorry but I don't have this path on my local comp. Never use absolute path.

2021-11-11 22:43 UTC, creator-max commented on AutoPark/Collections.cs
> +            LoadRents(rentsPath);
Thanks, fixed

2021-11-11 22:43 UTC, creator-max commented on AutoPark/Collections.cs
> +        public List<Vehicle> ListVehicle { get; }
fixed

2021-11-11 22:43 UTC, creator-max commented on AutoPark/Program.cs
> +            const string path = @"C:\Users\ASUS\source\repos\AutoPark\AutoPark\Data\";
fixed

2021-11-14 14:48 UTC, PushMeNow requested changes

2021-11-14 14:48 UTC, PushMeNow commented on AutoPark/Program.cs
> +            string path = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, @"..\..\..\Data\"));
Again bad solution. These files must be copied on compile and you have to get them from base directory.

2021-11-14 15:42 UTC, creator-max commented on AutoPark/Program.cs
> +            string path = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, @"..\..\..\Data\"));
Added

2021-11-14 20:50 UTC, PushMeNow approved these changes

2021-11-14 22:36 UTC, kuzmiich approved these changes
good job

2021-11-15 09:00 UTC, merged