Make level-6.
creator-max/AutoPark pull request #7
Opened 2021-11-15 09:02 UTC by creator-max

Add a queue at the car wash.

2021-11-15 20:00 UTC, PushMeNow requested changes

2021-11-15 20:00 UTC, PushMeNow commented on AutoPark/CarWash/MyQueue.cs
> +            }
Actually this check is useless because you will initialize queue in any case.

2021-11-15 20:00 UTC, PushMeNow commented on AutoPark/CarWash/MyQueue.cs
> +            if(Count == 0)
I don't understand why do you need this condition. You can just write:
<pre>
_queue[_lastIndex] = item;
_lastIndex++;
</pre>

2021-11-15 20:00 UTC, PushMeNow commented on AutoPark/CarWash/MyQueue.cs
> +        private int _lastIndex;
I understand why do you need _lastIndex but not _firstIndex. For me it is useless because you have to recreate your array on each dequeue operation.

2021-11-15 20:00 UTC, PushMeNow commented on AutoPark/CarWash/MyQueue.cs
> +            _firstIndex++;
Here just recreate your array with length - 1

2021-11-17 19:44 UTC, PushMeNow approved these changes

2021-11-17 20:14 UTC, creator-max commented on AutoPark/CarWash/MyQueue.cs
> +            if(Count == 0)
fixed

2021-11-17 20:14 UTC, creator-max commented on AutoPark/CarWash/MyQueue.cs
> +        private int _lastIndex;
fixed

2021-11-17 20:15 UTC, creator-max commented on AutoPark/CarWash/MyQueue.cs
> +            }
fixed

2021-11-17 20:15 UTC, creator-max commented on AutoPark/CarWash/MyQueue.cs
> +                SetCapacity(_queue.Length * 2);
fixed

2021-11-18 16:34 UTC, kuzmiich approved these changes

2021-11-20 19:25 UTC, merged