Add stack.
creator-max/AutoPark pull request #8
Opened 2021-11-18 14:25 UTC by creator-max

Added a stack for the garage.

2021-11-18 16:48 UTC, PushMeNow requested changes

2021-11-18 16:48 UTC, PushMeNow commented on AutoPark/Garage/MyStack.cs
> +            Array.Copy(_stack, newStack, --_headIndex);
Actually I don't see the reason to recreate array

2021-11-18 16:48 UTC, PushMeNow commented on AutoPark/Garage/MyStack.cs
> +        public int Count => _headIndex;
Count != headIndex

2021-11-18 18:51 UTC, kuzmiich approved these changes
good job. Could replace `==` to `is`

2021-11-19 16:45 UTC, creator-max commented on AutoPark/Garage/MyStack.cs
> +            if (collection == null)
Replaced

2021-11-19 16:46 UTC, creator-max commented on AutoPark/Garage/MyStack.cs
> +            Array.Copy(_stack, newStack, --_headIndex);
I agree. Thanks, fixed.

2021-11-19 16:48 UTC, creator-max commented on AutoPark/Garage/MyStack.cs
> +        public int Count => _headIndex;
Refused to use _headIndex.

2021-11-20 18:34 UTC, PushMeNow approved these changes

2021-11-20 19:22 UTC, merged